export const metricLabels = {
  agencies: "Agencies",
  agencyAssignments: "Agency Assignments",
  arrests: "Arrests",
  budget: "Budget",
  caseOutcomes: "Case Outcomes",
  caseTypes: "Case Types",
  civilCases: "Civil Cases",
  currentSalary: "Current Salary",
  daylightNighttimeStops: "Daylight vs Nighttime Stops",
  federalAgencies: "Federal Agencies",
  judgments: "Judgments",
  latestCaseActivity: "Latest Case Activity",
  latestFiscalYear: "Latest Fiscal Year",
  latestPersonnelUpdate: "Latest Personnel Update",
  latestRecordedYear: "Latest Recorded Year",
  liabilityCosts: "Liability Costs",
  killings: "Killings",
  operatingSpend: "Operating Spend",
  overtime: "Overtime",
  personnel: "Personnel",
  personnelRecords: "Personnel Records",
  racialBreakdownStopsArrests: "Racial Breakdown of Stops or Arrests",
  reports: "Reports",
  settlements: "Settlements",
  topChargeCategories: "Top Charge Categories",
  totalTimeAsOfficer: "Total Time as Officer",
} as const;
